// Generated by CoffeeScript 1.6.3
var ExperienceLevel, experienceLevelModel, mongo;

mongo = require('../lib/mongo');

ExperienceLevel = new mongo.Schema({
  name: {
    type: String,
    "default": '',
    trim: true
  },
  conferenceId: Number
});

experienceLevelModel = mongo.client.model('ExperienceLevel', ExperienceLevel);

module.exports = experienceLevelModel;

/*
//@ sourceMappingURL=experienceLevel.map
*/
