// Generated by CoffeeScript 1.6.3
var Cache, OAuth, async, config, db, moment, request, syncWordpress, syncWordpressPosts, syncWordpressPostsTask, syncWordpressTask, util, utils, _;

util = require('util');

async = require('async');

moment = require("moment");

request = require("request");

OAuth = require('oauth');

_ = require('underscore')._;

config = require("../../conf/config");

utils = require('../../lib/utils');

Cache = require('../../lib/cache');

db = require("../../db");

syncWordpressTask = require('../../task/syncWordpress');

syncWordpressPostsTask = require('../../task/syncWordpressPosts');

syncWordpress = function(req, res) {
  syncWordpressTask.synchronize();
  return res.send(200, "Started sync for wordpress data");
};

syncWordpressPosts = function(req, res) {
  syncWordpressPostsTask.synchronize();
  return res.send(200, "Started sync for wordpress posts");
};

module.exports = {
  syncWordpress: syncWordpress,
  syncWordpressPosts: syncWordpressPosts
};

/*
//@ sourceMappingURL=index.map
*/
