// Generated by CoffeeScript 1.6.3
var News, apns, async, config, db, moment, processWordpressRecentBlogPosts, request, synchronize, synchronizeWordpressNews, utils, _;

utils = require('../lib/utils');

async = require('async');

_ = require('underscore')._;

News = require("../model/news");

db = require("../db");

moment = require("moment");

config = require("../conf/config");

request = require("request");

apns = require("../lib/apns");

synchronize = function() {
  var callback;
  callback = function(err, news) {
    if (err) {
      return console.log("Wordpress Synchronization ended with error: " + err.message + " - Error: " + err);
    } else {
      return console.log("Wordpress Synchronization ended with success ! (" + news.length + " blog posts synchronized)");
    }
  };
  if (config.feature.stopWatch) {
    callback = utils.stopWatchCallbak(callback);
  }
  console.log("Start synchronizing Wordpress blog post entries ...");
  return processWordpressRecentBlogPosts(callback);
};

processWordpressRecentBlogPosts = function(callback) {
  return request.get({
    url: "http://blog.xebia.fr/wp-json-api/get_recent_posts?count=50",
    json: true
  }, function(error, data, response) {
    return async.map(response.posts, synchronizeWordpressNews, callback);
  });
};

synchronizeWordpressNews = function(post, callback) {
  return News.findOne({
    type: 'wordpress',
    typeId: post.id
  }, function(err, news) {
    var newsEntry, _ref, _ref1;
    if (err) {
      return callback(err);
    } else if (!news) {
      newsEntry = new News({
        content: post.excerpt,
        draft: false,
        imageUrl: (post != null ? post.attachments : void 0) && post.attachments.length > 0 ? (post != null ? (_ref = post.attachments[0].images) != null ? (_ref1 = _ref.full) != null ? _ref1.url : void 0 : void 0 : void 0) || "" : "",
        publicationDate: post.date,
        targetUrl: post.url,
        title: post.title_plain,
        author: post.author.name,
        type: "wordpress",
        typeId: post.id
      });
      return newsEntry.save(function(err) {
        return callback(err, newsEntry);
      });
    } else {
      return callback(err, void 0);
    }
  });
};

module.exports = {
  synchronize: synchronize
};

/*
//@ sourceMappingURL=syncWordpressNews.map
*/
