language: node_js
node_js:
  - 0.10
services: mongodb
before_script:
  - npm install -g grunt-cli
script: grunt cover
env:
  global:
  - LC_ALL="en_US.UTF-8"
notifications:
  recipients:
  - akinsella@xebia.fr
