// Generated by CoffeeScript 1.6.2
var ECT, GoogleStrategy, MongoStore, allowCrossDomain, app, auth, config, ectRenderer, eventbrite, express, fs, github, mongo, news, passport, path, requestLogger, routes, sass, security, twitter, util, utils, wordpress,
  _this = this;

fs = require('fs');

path = require('path');

express = require('express');

passport = require('passport');

util = require('util');

GoogleStrategy = require('passport-google').Strategy;

sass = require('node-sass');

MongoStore = require('connect-mongo')(express);

mongo = require('./lib/mongo');

requestLogger = require('./lib/requestLogger');

allowCrossDomain = require('./lib/allowCrossDomain');

utils = require('./lib/utils');

security = require('./lib/security');

config = require('./conf/config');

routes = require('./routes');

github = require('./routes/github');

twitter = require('./routes/twitter');

eventbrite = require('./routes/eventbrite');

wordpress = require('./routes/wordpress');

auth = require('./routes/auth');

news = require('./routes/news');

ECT = require('ect');

ectRenderer = ECT({
  cache: true,
  watch: true,
  root: "views"
});

console.log("Application Name: " + config.cf.app.name);

console.log("Env: " + (JSON.stringify(config.cf)));

passport.serializeUser(function(user, done) {
  return done(null, user);
});

passport.deserializeUser(function(obj, done) {
  return done(null, obj);
});

passport.use(new GoogleStrategy({
  returnURL: 'http://localhost:9000/auth/google/return',
  realm: 'http://localhost:9000/'
}, function(identifier, profile, done) {
  return process.nextTick(function() {
    profile.identifier = identifier;
    return done(null, profile);
  });
}));

app = express();

app.configure(function() {
  console.log("Environment: " + (app.get('env')));
  app.set('port', config.cf.port || process.env.PORT || 9000);
  app.set('views', "" + __dirname + "/views");
  app.engine('.ect', ectRenderer.render);
  app.use('/images', express["static"]("" + __dirname + "/public/images"));
  app.use('/scripts', express["static"]("" + __dirname + "/public/scripts"));
  app.use('/styles', express["static"]("" + __dirname + "/public/styles"));
  app.use(express.favicon());
  app.use(express.bodyParser());
  app.use(express.cookieParser());
  app.use(express.session({
    secret: config.cf.app.instance_id,
    maxAge: new Date(Date.now() + 3600000),
    store: new MongoStore({
      db: config.mongoConfig.credentials.name,
      host: config.mongoConfig.credentials.host,
      port: config.mongoConfig.credentials.port,
      username: config.mongoConfig.credentials.username,
      password: config.mongoConfig.credentials.password,
      collection: "sessions",
      auto_reconnect: true
    })
  }));
  app.use(express.logger());
  app.use(express.methodOverride());
  app.use(allowCrossDomain());
  app.set('running in cloud', config.cf.cloud);
  app.use(requestLogger());
  app.use(passport.initialize());
  app.use(passport.session());
  app.use(app.router);
  app.use(function(err, req, res, next) {
    console.error("Error: " + err + ", Stacktrace: " + err.stack);
    return res.send(500, "Something broke! Error: " + err + ", Stacktrace: " + err.stack);
  });
});

app.configure('development', function() {
  app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure('production', function() {
  app.use(express.errorHandler());
});

app.get('/', routes.index);

app.get('/api/eventbrite/list', eventbrite.list);

app.get('/api/github/orgs/xebia-france/repos', github.repos);

app.get('/api/github/orgs/xebia-france/public_members', github.public_members);

app.get('/api/twitter/auth/stream/XebiaFr', twitter.stream_xebiafr);

app.get('/api/twitter/auth/user/:user', twitter.user_timeline_authenticated);

app.get('/api/twitter/user/:user', twitter.user_timeline);

app.get('/api/wordpress/post/recent', wordpress.recentPosts);

app.get('/api/wordpress/post/:id', wordpress.post);

app.get('/api/wordpress/authors', wordpress.authors);

app.get('/api/wordpress/author/:author', wordpress.authorPosts);

app.get('/api/wordpress/tags', wordpress.tags);

app.get('/api/wordpress/tag/:tag', wordpress.tagPosts);

app.get('/api/wordpress/categories', wordpress.categories);

app.get('/api/wordpress/category/:category', wordpress.categoryPosts);

app.get('/api/wordpress/dates', wordpress.dates);

app.get('/api/wordpress/:year/:month', wordpress.datePosts);

app.post('/api/news/create', news.create);

app.get('/api/news/list', news.list);

app.get('/api/news/:id', news.item);

app.get('/account', security.ensureAuthenticated, auth.account);

app.get('/login', auth.login);

app.get('/auth/google', passport.authenticate('google', {
  failureRedirect: '/login'
}), auth.auth_google);

app.get('/auth/google/return', passport.authenticate('google', {
  failureRedirect: '/login'
}), auth.auth_google_return);

app.get('/logout', auth.logout);

process.on('SIGTERM', function() {
  console.log('Got SIGTERM exiting...');
  return process.exit(0);
});

process.on('uncaughtException', function(err) {
  console.error("An uncaughtException was found, the program will end. " + err + ", stacktrace: " + err.stack);
  return process.exit(1);
});

console.log("Express listening on port: " + (app.get('port')));

app.listen(app.get('port'));

console.log('Initializing xebia-mobile-backend application');
