// Generated by CoffeeScript 1.6.2
var me, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

me = function(req, res) {
  return res.json({
    user_id: req.user.id,
    name: req.user.name,
    scope: req.authInfo.scope
  });
};

module.exports = {
  me: me
};
