// Generated by CoffeeScript 1.6.3
var cards, cardsData, categories, fs, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

fs = require('fs');

cardsData = JSON.parse(fs.readFileSync("" + __dirname + "/../data/cards.json", "utf-8"));

cards = function() {
  return cardsData;
};

categories = function() {
  return categories = {
    categories: _.chain(cardsData.cards).pluck("category").uniq(false, function(category) {
      return category.id;
    }).value()
  };
};

module.exports = {
  cards: cards,
  categories: categories
};
