// Generated by CoffeeScript 1.6.3
var cards, cardsData, categories, categoriesData, fs, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

fs = require('fs');

cardsData = JSON.parse(fs.readFileSync("" + __dirname + "/../data/cards.json", "utf-8"));

categoriesData = JSON.parse(fs.readFileSync("" + __dirname + "/../data/categories.json", "utf-8"));

cards = function() {
  return cardsData;
};

categories = function() {
  return categoriesData;
};

module.exports = {
  cards: cards,
  categories: categories
};
