// Generated by CoffeeScript 1.6.3
var cards, cardsData, fs, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

fs = require('fs');

cardsData = JSON.parse(fs.readFileSync("" + __dirname + "/../data/cards.json", "utf-8"));

cards = function() {
  return cardsData;
};

module.exports = {
  cards: cards
};
