// Generated by CoffeeScript 1.6.3
var DevoxxDataArraySynchronizer, DevoxxEventAwareDataArraySynchronizer,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

DevoxxDataArraySynchronizer = require('./DevoxxDataArraySynchronizer');

DevoxxEventAwareDataArraySynchronizer = (function(_super) {
  __extends(DevoxxEventAwareDataArraySynchronizer, _super);

  function DevoxxEventAwareDataArraySynchronizer(name, eventId) {
    this.name = name;
    this.eventId = eventId;
    console.log("Instanciating Devoxx Event Aware Data Array Synchronizer with name: '" + this.name + "' and eventId: '" + this.eventId + "'");
    DevoxxEventAwareDataArraySynchronizer.__super__.constructor.call(this, name);
  }

  DevoxxEventAwareDataArraySynchronizer.prototype.baseUrl = function() {
    return "http://dev.cfp.devoxx.com:3000/rest/v1/events/" + this.eventId;
  };

  return DevoxxEventAwareDataArraySynchronizer;

})(DevoxxDataArraySynchronizer);

module.exports = DevoxxEventAwareDataArraySynchronizer;

/*
//@ sourceMappingURL=DevoxxEventAwareDataArraySynchronizer.map
*/
