// Generated by CoffeeScript 1.6.3
var config, localConfig, underscore, _;

underscore = require('underscore');

_ = underscore._;

if (!config) {
  localConfig = {
    offlineMode: process.env.OFFLINE_MODE === "true",
    hostname: process.env.APP_HOSTNAME,
    port: process.env.APP_HTTP_PORT,
    appname: 'xebia-mobile-backend.helyx.org',
    devMode: process.env.DEV_MODE === "true",
    verbose: true,
    processNumber: process.env.INDEX_OF_PROCESS || 0,
    scheduler: {
      syncWordpress: {
        cron: '0 0,15,30,45 * * * 1-7',
        timezone: "Europe/Paris",
        runOnStart: true
      }
    },
    auth: {
      google: {
        callbackUrl: process.env.AUTH_GOOGLE_CALLBACK_URL,
        realm: process.env.AUTH_GOOGLE_REALM
      }
    },
    mongo: {
      dbname: process.env.MONGO_DBNAME,
      hostname: process.env.MONGO_HOSTNAME,
      port: process.env.MONGO_PORT,
      username: process.env.MONGO_USERNAME,
      password: process.env.MONGO_PASSWORD
    },
    monitoring: {
      newrelic: {
        apiKey: process.env.NEW_RELIC_API_KEY
      },
      strongOps: {
        apiKey: process.env.STRONG_OPS_API_KEY
      },
      nodetime: {
        apiKey: process.env.NODETIME_API_KEY
      }
    },
    feature: {
      stopWatch: true
    }
  };
  config = _.extend({}, localConfig);
}

module.exports = {
  offlineMode: config.offlineMode,
  devMode: config.devMode,
  verbose: config.verbose,
  hostname: config.hostname,
  processNumber: config.processNumber,
  port: config.port,
  appname: config.appname,
  auth: config.auth,
  uri: config.uri,
  mongo: config.mongo,
  monitoring: config.monitoring,
  feature: config.feature,
  scheduler: config.scheduler
};

/*
//@ sourceMappingURL=config.map
*/
