// Generated by CoffeeScript 1.6.2
var config, redis, redisClient;

config = require('../conf/config');

redis = require('redis');

redis.debug_mode = false;

redisClient = redis.createClient(config.redisConfig.credentials.port, config.redisConfig.credentials.hostname);

if (config.redisConfig.credentials.password) {
  redisClient.auth(config.redisConfig.credentials.password, function(err, res) {
    return console.log("Authenticating to redis!");
  });
}

redisClient.on("error", function(err) {
  return console.log("Error " + err);
});

module.exports = {
  client: redisClient
};
