// Generated by CoffeeScript 1.6.3
var ensureAuthenticated,
  _this = this;

ensureAuthenticated = function(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  } else {
    res.send(401, "Unauthorized");
  }
};

module.exports = {
  ensureAuthenticated: ensureAuthenticated
};

/*
//@ sourceMappingURL=security.map
*/
