// Generated by CoffeeScript 1.6.3
var AccessToken, apn, find, save, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

apn = require('apn');

AccessToken = require("../model/accessToken");

find = function(token, done) {
  return AccessToken.find({
    token: token
  }, function(err, accessToken) {
    return done(err, accessToken);
  });
};

save = function(token, userID, clientID, done) {
  var accessToken;
  accessToken = new AccessToken({
    userID: userID,
    clientID: clientID
  });
  return accessToken.save(function(err) {
    return done(err, accessToken);
  });
};

module.exports = {
  find: find,
  save: save
};

/*
//@ sourceMappingURL=accessTokens.map
*/
