// Generated by CoffeeScript 1.6.2
var codes;

codes = {};

exports.find = function(key, done) {
  var code;

  code = codes[key];
  return done(null, code);
};

exports.save = function(code, clientID, redirectURI, userID, done) {
  codes[code] = {
    clientID: clientID,
    redirectURI: redirectURI,
    userID: userID
  };
  return done(null);
};
