// Generated by CoffeeScript 1.6.3
var AuthorizationCode, apn, find, save, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

apn = require('apn');

AuthorizationCode = require("../model/authorizationCode");

find = function(code, done) {
  return AuthorizationCode.find({
    code: code
  }, function(err, authorizationCode) {
    if (err) {
      return done(err, authorizationCode);
    }
  });
};

save = function(code, clientID, redirectURI, userID, done) {
  var authorizationCode;
  authorizationCode = new AuthorizationCode({
    clientID: clientID,
    redirectURI: redirectURI,
    userID: userID
  });
  return authorizationCode.save(function(err) {
    return done(err, authorizationCode);
  });
};

module.exports = {
  find: find,
  save: save
};

/*
//@ sourceMappingURL=authorizationCodes.map
*/
