// Generated by CoffeeScript 1.6.3
var Client, apn, find, findById, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

apn = require('apn');

Client = require("../model/client");

find = function(id, done) {
  return Client.find({
    id: id
  }, function(err, client) {
    return done(err, client);
  });
};

findById = function(clientId, done) {
  return Client.find({
    clientId: clientId
  }, function(err, client) {
    return done(err, client);
  });
};

module.exports = {
  find: find,
  findById: findById
};

/*
//@ sourceMappingURL=clients.map
*/
