// Generated by CoffeeScript 1.6.2
var clients;

clients = [
  {
    id: "1",
    name: "Xebia-iOS",
    clientId: "xebia-ios",
    clientSecret: "1L3J1K4U930J.4LKlk1J4H1J34f!13H4KJ14Hlkj;31"
  }
];

exports.find = function(id, done) {
  var client, i, len;

  i = 0;
  len = clients.length;
  while (i < len) {
    client = clients[i];
    if (client.id === id) {
      return done(null, client);
    }
    i++;
  }
  return done(null, null);
};

exports.findByClientId = function(clientId, done) {
  var client, i, len;

  i = 0;
  len = clients.length;
  while (i < len) {
    client = clients[i];
    if (client.clientId === clientId) {
      return done(null, client);
    }
    i++;
  }
  return done(null, null);
};
