// Generated by CoffeeScript 1.6.2
var clients;

clients = [
  {
    id: "1",
    name: "Samplr",
    clientId: "abc123",
    clientSecret: "ssh-secret"
  }
];

exports.find = function(id, done) {
  var client, i, len;

  i = 0;
  len = clients.length;
  while (i < len) {
    client = clients[i];
    if (client.id === id) {
      return done(null, client);
    }
    i++;
  }
  return done(null, null);
};

exports.findByClientId = function(clientId, done) {
  var client, i, len;

  i = 0;
  len = clients.length;
  while (i < len) {
    client = clients[i];
    if (client.clientId === clientId) {
      return done(null, client);
    }
    i++;
  }
  return done(null, null);
};
