// Generated by CoffeeScript 1.6.2
var users;

users = [
  {
    id: "1",
    username: "bob",
    password: "secret",
    name: "Bob Smith"
  }, {
    id: "2",
    username: "joe",
    password: "password",
    name: "Joe Davis"
  }
];

exports.find = function(id, done) {
  var i, len, user;

  i = 0;
  len = users.length;
  while (i < len) {
    user = users[i];
    if (user.id === id) {
      return done(null, user);
    }
    i++;
  }
  return done(null, null);
};

exports.findByUsername = function(username, done) {
  var i, len, user;

  i = 0;
  len = users.length;
  while (i < len) {
    user = users[i];
    if (user.username === username) {
      return done(null, user);
    }
    i++;
  }
  return done(null, null);
};
