// Generated by CoffeeScript 1.6.3
var User, apn, check, findAll, findByEmail, findById, removeById, utils, validate, _;

utils = require('../lib/utils');

_ = require('underscore')._;

apn = require('apn');

User = require("../model/user");

check = require("validator").check;

findById = function(id, done) {
  return User.find({
    id: id
  }, function(err, user) {
    return done(err, user);
  });
};

findByEmail = function(email, done) {
  return User.findOne({
    email: email
  }, function(err, user) {
    return done(err, user);
  });
};

removeById = function(userId, done) {
  return User.remove({
    id: userId
  }, function(err, user) {
    return done(err, user);
  });
};

validate = function(user) {
  check(user.username, 'Username must be 1-20 characters long').len(1, 20);
  return check(user.password, 'Password must be 5-60 characters long').len(5, 60);
};

findAll = function(done) {
  return User.find({}).exec(function(err, data) {
    return done(err, data);
  });
};

module.exports = {
  findAll: findAll,
  findById: findById,
  findByEmail: findByEmail,
  removeById: removeById
};

/*
//@ sourceMappingURL=users.map
*/
