// Generated by CoffeeScript 1.6.3
var informations;

informations = function(req, res) {
  return res.json({
    minApiVersion: "1"
  });
};

module.exports = {
  informations: informations
};

/*
//@ sourceMappingURL=api.map
*/
