// Generated by CoffeeScript 1.6.3
var account, authGoogleCallback, login, logout, passport, security, utils,
  _this = this;

utils = require('../lib/utils');

security = require('../lib/security');

passport = require('passport');

account = function(req, res) {
  return res.render('account', {
    user: req.user
  });
};

login = passport.authenticate('local', function(req, res) {
  return res.send(200, "User authenticated");
});

logout = function(req, res) {
  req.logout();
  return res.send(200, "User logged out");
};

authGoogleCallback = function(req, res) {
  return res.redirect("/#/login");
};

module.exports = {
  account: account,
  login: login,
  authGoogleCallback: authGoogleCallback,
  logout: logout
};

/*
//@ sourceMappingURL=auth.map
*/
