// Generated by CoffeeScript 1.6.3
var authGoogleCallback, login, loginForm, logout, passport, security, utils,
  _this = this;

utils = require('../lib/utils');

security = require('../lib/security');

passport = require('passport');

login = passport.authenticate('local', function(req, res) {
  return res.redirect("/");
});

loginForm = function(req, res) {
  return res.redirect("/login.html");
};

logout = function(req, res) {
  req.logout();
  return res.redirect("/login");
};

authGoogleCallback = function(req, res) {
  return res.redirect("/");
};

module.exports = {
  loginForm: loginForm,
  login: login,
  logout: logout,
  authGoogleCallback: authGoogleCallback
};

/*
//@ sourceMappingURL=auth.map
*/
