// Generated by CoffeeScript 1.6.3
var account, authGoogle, authGoogleCallback, login, loginForm, logout, passport, security, utils,
  _this = this;

utils = require('../lib/utils');

security = require('../lib/security');

passport = require('passport');

account = function(req, res) {
  return res.render('account', {
    user: req.user
  });
};

loginForm = function(req, res) {
  return res.render("login");
};

login = passport.authenticate('local', {
  successRedirect: '/',
  failureRedirect: '/login'
});

logout = function(req, res) {
  req.logout();
  return res.redirect("/login");
};

authGoogle = function(req, res) {
  res.redirect('/');
};

authGoogleCallback = function(req, res) {
  res.redirect('/');
};

module.exports = {
  account: account,
  login: login,
  loginForm: loginForm,
  authGoogle: authGoogle,
  authGoogleCallback: authGoogleCallback,
  logout: logout
};

/*
//@ sourceMappingURL=auth.map
*/
