// Generated by CoffeeScript 1.6.3
var cardById, cardService, cards, cardsByCategoryId, categories, config, fs, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

cardService = require('../service/cardService');

config = require('../conf/config');

fs = require('fs');

cards = function(req, res) {
  res.charset = 'UTF-8';
  cards = cardService.cards();
  return utils.responseData(200, "", cards, {
    req: req,
    res: res
  });
};

categories = function(req, res) {
  res.charset = 'UTF-8';
  if (config.offlineMode) {
    return res.send(JSON.parse(fs.readFileSync("" + __dirname + "/../data/essentials_category.json", "utf-8")));
  } else {
    categories = cardService.categories();
    return utils.responseData(200, "", categories, {
      req: req,
      res: res
    });
  }
};

cardsByCategoryId = function(req, res) {
  var category, categoryId, data;
  res.charset = 'UTF-8';
  if (config.offlineMode) {
    return res.send(JSON.parse(fs.readFileSync("" + __dirname + "/../data/essentials_category_architecture_design.json", "utf-8")));
  } else {
    categoryId = req.params.id;
    category = _(cardService.categories().categories).find(function(category) {
      return category.id === categoryId;
    });
    cards = _(cardService.cards().cards).filter(function(card) {
      return card.category.id === categoryId;
    });
    data = {
      category: category,
      cards: cards
    };
    return utils.responseData(200, "", data, {
      req: req,
      res: res
    });
  }
};

cardById = function(req, res) {
  var cardId;
  res.charset = 'UTF-8';
  cardId = req.params.id;
  cards = _(cardService.cards().cards).find(function(card) {
    return card.id === cardId;
  });
  return utils.responseData(200, "", cards, {
    req: req,
    res: res
  });
};

module.exports = {
  cards: cards,
  cardById: cardById,
  categories: categories,
  cardsByCategoryId: cardsByCategoryId
};

/*
//@ sourceMappingURL=card.map
*/
