// Generated by CoffeeScript 1.6.3
var Card, cards, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

Card = require('../service/card');

cards = function(req, res) {
  cards = Card.cards();
  return utils.responseData(200, "", cards, {
    req: req,
    res: res
  });
};

module.exports = {
  cards: cards
};
