// Generated by CoffeeScript 1.6.3
var Device, apn, create, findById, list, mapDevice, register, removeById, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

apn = require('apn');

Device = require("../model/device");

create = function(req, res) {
  var device;
  device = new Device({
    udid: req.body.udid,
    token: req.body.token,
    osType: req.body.osType,
    osVersion: req.body.osVersion
  });
  return device.save(function(err) {
    if (err) {
      return utils.responseData(500, "Could not save device", req.body, {
        req: req,
        res: res
      });
    } else {
      return utils.responseData(201, "Created", mapDevice(device), {
        req: req,
        res: res
      });
    }
  });
};

register = function(req, res) {
  return Device.findOne({
    udid: req.body.udid,
    token: req.body.token
  }, function(err, device) {
    if (err) {
      return utils.responseData(500, "Could not check device is already registered", void 0, {
        req: req,
        res: res
      });
    } else if (device) {
      return utils.responseData(200, "Device is already registered", mapDevice(device), {
        req: req,
        res: res
      });
    } else {
      device = new Device({
        udid: req.body.udid,
        token: req.body.token,
        osType: req.body.osType,
        osVersion: req.body.osVersion
      });
      return device.save(function(err) {
        if (err) {
          return utils.responseData(500, "Could not save device", req.body, {
            req: req,
            res: res
          });
        } else {
          return utils.responseData(201, "Created", mapDevice(device), {
            req: req,
            res: res
          });
        }
      });
    }
  });
};

list = function(req, res) {
  return Device.find({}, function(err, devices) {
    if (err) {
      return utils.responseData(500, "Could not get device list", void 0, {
        req: req,
        res: res
      });
    } else {
      return utils.responseData(200, void 0, devices.map(mapDevice), {
        req: req,
        res: res
      });
    }
  });
};

findById = function(req, res) {
  return Device.findOne({
    id: req.params.id
  }, function(err, device) {
    if (err) {
      return utils.responseData(500, "Could not get device", void 0, {
        req: req,
        res: res
      });
    } else if (!device) {
      return utils.responseData(404, "Not Found", void 0, {
        req: req,
        res: res
      });
    } else {
      return utils.responseData(200, void 0, mapDevice(device), {
        req: req,
        res: res
      });
    }
  });
};

removeById = function(req, res) {
  return Device.findOneAndRemove({
    id: req.params.id
  }, function(err, device) {
    if (device) {
      return utils.responseData(204, void 0, mapDevice(device), {
        req: req,
        res: res
      });
    } else {
      return utils.responseData(404, "Not Found", void 0, {
        req: req,
        res: res
      });
    }
  });
};

mapDevice = function(device) {
  return {
    id: device.id,
    token: device.token,
    udid: device.udid
  };
};

module.exports = {
  register: register,
  list: list,
  findById: findById,
  create: create,
  removeById: removeById
};

/*
//@ sourceMappingURL=device.map
*/
