// Generated by CoffeeScript 1.6.3
var News, create, findById, list, removeById, utils, _;

utils = require('../lib/utils');

News = require('../model/news');

_ = require('underscore')._;

list = function(req, res) {
  return News.find({}, function(err, news) {
    utils.responseData(200, void 0, news, {
      req: req,
      res: res
    });
  });
};

findById = function(req, res) {
  return News.findOne({
    id: req.params.id
  }, function(err, news) {
    if (news) {
      utils.responseData(200, void 0, news, {
        req: req,
        res: res
      });
    } else {
      utils.responseData(404, "Not Found", void 0, {
        req: req,
        res: res
      });
    }
  });
};

removeById = function(req, res) {
  return News.findOneAndRemove({
    id: req.params.id
  }, function(err, news) {
    if (news) {
      utils.responseData(204, void 0, news, {
        req: req,
        res: res
      });
    } else {
      utils.responseData(404, "Not Found", void 0, {
        req: req,
        res: res
      });
    }
  });
};

create = function(req, res) {
  var news;
  news = new News(req.body);
  return news.save(function(err) {
    if (err) {
      utils.responseData(500, "Could not save news", req.body, {
        req: req,
        res: res
      });
    } else {
      utils.responseData(201, "Created", news, {
        req: req,
        res: res
      });
    }
  });
};

module.exports = {
  list: list,
  findById: findById,
  create: create,
  removeById: removeById
};
