// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/

var account, index, login, loginForm, logout, passport,
  _this = this;

passport = require('passport');

index = function(req, res) {
  return res.send("OAuth 2.0 Server");
};

account = function(req, res) {
  return res.render('account', {
    user: req.user
  });
};

loginForm = function(req, res) {
  return res.render("login");
};

login = passport.authenticate('local', {
  successRedirect: '/',
  failureRedirect: '/login'
});

logout = function(req, res) {
  req.logout();
  return res.redirect("/login");
};

module.exports = {
  index: index,
  account: account,
  login: login,
  loginForm: loginForm,
  logout: logout
};

/*
//@ sourceMappingURL=site.map
*/
