// Generated by CoffeeScript 1.6.3
var User, apn, create, findById, list, me, removeById, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

apn = require('apn');

User = require("../model/user");

create = function(req, res) {
  var user;
  user = new User(req.body);
  user.save(function(err) {
    if (err) {
      return utils.responseData(500, "Could not save user", req.body, {
        req: req,
        res: res
      });
    } else {
      return utils.responseData(201, "Created", user, {
        req: req,
        res: res
      });
    }
  });
};

list = function(req, res) {
  User.find({}, function(err, users) {
    return utils.responseData(200, void 0, users, {
      req: req,
      res: res
    });
  });
};

findById = function(req, res) {
  User.findOne({
    id: req.params.id
  }, function(err, user) {
    if (user) {
      return utils.responseData(200, void 0, user, {
        req: req,
        res: res
      });
    } else {
      return utils.responseData(404, "Not Found", void 0, {
        req: req,
        res: res
      });
    }
  });
};

removeById = function(req, res) {
  User.findOneAndRemove({
    id: req.params.id
  }, function(err, user) {
    if (user) {
      return utils.responseData(204, void 0, user, {
        req: req,
        res: res
      });
    } else {
      return utils.responseData(404, "Not Found", void 0, {
        req: req,
        res: res
      });
    }
  });
};

me = function(req, res) {
  return res.json({
    id: req.user.id,
    username: req.user.username,
    email: req.user.email,
    gender: req.user.gender,
    firstName: req.user.firstName,
    lastName: req.user.lastName,
    role: req.user.role
  });
};

module.exports = {
  create: create,
  list: list,
  findById: findById,
  create: create,
  removeById: removeById,
  me: me
};

/*
//@ sourceMappingURL=user.map
*/
