// Generated by CoffeeScript 1.6.3
var authorPosts, authors, categories, categoryPosts, datePosts, dates, post, processRequest, recentPosts, tagPosts, tags, utils, _;

utils = require('../lib/utils');

_ = require('underscore')._;

processRequest = function(req, res, url, transform) {
  var options;
  options = utils.buildOptions(req, res, url, 10 * 24 * 60 * 60, transform);
  utils.processRequest(options);
};

authors = function(req, res) {
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_author_index?count=250", function(data) {
    delete data.status;
    _(data.authors).each(function(author) {
      author.firstname = author.first_name;
      delete author.first_name;
      author.lastname = author.last_name;
      delete author.last_name;
    });
    return data;
  });
};

tags = function(req, res) {
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_tag_index/?count=2000", function(data) {
    delete data.status;
    _(data.tags).each(function(tag) {
      tag.postCount = tag.post_count;
      delete tag.post_count;
    });
    return data;
  });
};

categories = function(req, res) {
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_category_index?count=100", function(data) {
    delete data.status;
    _(data.categories).each(function(category) {
      category.postCount = category.post_count;
      delete category.post_count;
    });
    return data;
  });
};

dates = function(req, res) {
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_date_index?count=1000", function(data) {
    var key, value, _ref;
    delete data.status;
    delete data.permalinks;
    _ref = data.tree;
    for (key in _ref) {
      value = _ref[key];
      data[key] = value;
    }
    delete data.tree;
    return data;
  });
};

post = function(req, res) {
  var postId;
  postId = req.params.id;
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_post?post_id=" + postId, function(data) {
    delete data.status;
    delete data.previous_url;
    delete data.next_url;
    data.post.titlePlain = data.post.title_plain;
    data.post.commentCount = data.post.comment_count;
    delete data.post.comment_count;
    data.post.commentStatus = data.post.comment_status;
    delete data.post.comment_status;
    delete data.post.title_plain;
    _(data.post.categories).each(function(category) {
      category.postCount = category.post_count;
      return delete category.post_count;
    });
    _(data.post.tags).each(function(tag) {
      tag.postCount = tag.post_count;
      return delete tag.post_count;
    });
    _(data.post.authors).each(function(author) {
      author.firstname = author.first_name;
      delete author.firstname;
      author.lastname = author.last_name;
      return delete author.last_name;
    });
    _(data.post.comments).each(function(author) {
      return delete author.parent;
    });
    return data.post;
  });
};

recentPosts = function(req, res) {
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_recent_posts", function(data) {
    delete data.status;
    post.total = post.title_plain;
    delete post.title_plain;
    _(data.posts).each(function(post) {
      post.titlePlain = post.title_plain;
      delete post.title_plain;
    });
    return data;
  });
};

authorPosts = function(req, res) {
  var authorId;
  authorId = req.params.id;
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_author_posts?id=" + authorId);
};

tagPosts = function(req, res) {
  var tagId;
  tagId = req.params.id;
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_tag_posts?id=" + tagId);
};

categoryPosts = function(req, res) {
  var categoryId;
  categoryId = req.params.id;
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_category_posts?id=" + categoryId);
};

datePosts = function(req, res) {
  var month, year;
  year = req.params.year;
  month = req.params.month;
  return processRequest(req, res, "http://blog.xebia.fr/wp-json-api/get_date_posts_sync_data/?date=" + year + month + "$&count=1000");
};

module.exports = {
  tags: tags,
  categories: categories,
  authors: authors,
  dates: dates,
  recentPosts: recentPosts,
  post: post,
  authorPosts: authorPosts,
  tagPosts: tagPosts,
  categoryPosts: categoryPosts,
  datePosts: datePosts
};

/*
//@ sourceMappingURL=wordpress.map
*/
